export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_GROCERIES = 'GET_GROCERIES';
export const GET_PACKAGES = 'GET_PACKAGES';
export const GET_SHELTERS = 'GET_SHELTERS';
export const STORE_SELECTED = 'STORE_SELECTED';
export const SHELTER_SELECTED = 'SHELTER_SELECTED';
